'''
Neuron simulator export for:

Components:
    Leak (Type: ionChannelPassive:  conductance=1.0E-11 (SI conductance))
    k_fast (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    k_slow (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    ca_boyle (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    ca_simple (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    CaPool (Type: fixedFactorConcentrationModel:  restingConc=0.0 (SI concentration) decayConstant=0.0115943 (SI time) rho=2.38919E-4 (SI rho_factor))
    neuron_to_neuron_exc_syn (Type: expTwoSynapse:  tauRise=0.001 (SI time) tauDecay=0.005 (SI time) peakTime=0.002011797390542625 (SI time) waveformFactor=1.8691859765265255 (dimensionless) gbase=1.0000000000000002E-10 (SI conductance) erev=0.0 (SI voltage))
    GenericMuscleCell (Type: cell)
    GenericNeuronCell (Type: cell)
    offset_current (Type: pulseGenerator:  delay=0.0 (SI time) duration=2.0 (SI time) amplitude=0.0 (SI current))
    MyNetwork (Type: network)
    sim_MyNetwork (Type: Simulation:  length=0.3 (SI time) step=1.0E-5 (SI time))


    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.11.0
         org.neuroml.model   v1.11.0
         jLEMS               v0.12.0

'''

import neuron

import time
import datetime
import sys

import hashlib
h = neuron.h
h.load_file("nrngui.hoc")

h("objref p")
h("p = new PythonObject()")

class NeuronSimulation():

    def __init__(self, tstop, dt=None, seed=123456789, abs_tol=None, rel_tol=None):

        print("\n    Starting simulation in NEURON of %sms generated from NeuroML2 model...\n"%tstop)

        self.setup_start = time.time()
        self.seed = seed
        self.abs_tol = abs_tol
        self.rel_tol = rel_tol
        self.randoms = []
        self.next_global_id = 0  # Used in Random123 classes for elements using random(), etc. 

        self.next_spiking_input_id = 0  # Used in Random123 classes for elements using random(), etc. 

        '''
        Adding simulation Component(id=sim_MyNetwork type=Simulation) of network/component: MyNetwork (Type: network)
        
        '''
        # ######################   Population: AVBR
        print("Population AVBR contains 1 instance(s) of component: GenericNeuronCell of type: cell")

        print("Setting the default initial concentrations for ca (used in GenericNeuronCell) to 0.0 mM (internal), 2.0 mM (external)")
        h("cai0_ca_ion = 0.0")
        h("cao0_ca_ion = 2.0")

        h.load_file("GenericNeuronCell.hoc")
        a_AVBR = []
        h("{ n_AVBR = 1 }")
        h("objectvar a_AVBR[n_AVBR]")
        for i in range(int(h.n_AVBR)):
            h("a_AVBR[%i] = new GenericNeuronCell()"%i)
            h("access a_AVBR[%i].soma"%i)

            self.next_global_id+=1

        h("{ a_AVBR[0].position(-4.581, -269.794, 37.863003) }")

        h("proc initialiseV_AVBR() { for i = 0, n_AVBR-1 { a_AVBR[i].set_initial_v() } }")
        h("objref fih_AVBR")
        h('{fih_AVBR = new FInitializeHandler(0, "initialiseV_AVBR()")}')

        h("proc initialiseIons_AVBR() { for i = 0, n_AVBR-1 { a_AVBR[i].set_initial_ion_properties() } }")
        h("objref fih_ion_AVBR")
        h('{fih_ion_AVBR = new FInitializeHandler(1, "initialiseIons_AVBR()")}')

        # ######################   Population: VD3
        print("Population VD3 contains 1 instance(s) of component: GenericNeuronCell of type: cell")

        print("Setting the default initial concentrations for ca (used in GenericNeuronCell) to 0.0 mM (internal), 2.0 mM (external)")
        h("cai0_ca_ion = 0.0")
        h("cao0_ca_ion = 2.0")

        h.load_file("GenericNeuronCell.hoc")
        a_VD3 = []
        h("{ n_VD3 = 1 }")
        h("objectvar a_VD3[n_VD3]")
        for i in range(int(h.n_VD3)):
            h("a_VD3[%i] = new GenericNeuronCell()"%i)
            h("access a_VD3[%i].soma"%i)

            self.next_global_id+=1

        h("{ a_VD3[0].position(-0.8, -188.1, -23.45) }")

        h("proc initialiseV_VD3() { for i = 0, n_VD3-1 { a_VD3[i].set_initial_v() } }")
        h("objref fih_VD3")
        h('{fih_VD3 = new FInitializeHandler(0, "initialiseV_VD3()")}')

        h("proc initialiseIons_VD3() { for i = 0, n_VD3-1 { a_VD3[i].set_initial_ion_properties() } }")
        h("objref fih_ion_VD3")
        h('{fih_ion_VD3 = new FInitializeHandler(1, "initialiseIons_VD3()")}')

        # ######################   Projection: NC_AVBR_VD3_Glutamate
        print("Adding projection: NC_AVBR_VD3_Glutamate, from AVBR to VD3 with synapse neuron_to_neuron_exc_syn, 1 connection(s)")

        h("objectvar syn_NC_AVBR_VD3_Glutamate_neuron_to_neuron_exc_syn[1]")

        h("objectvar netConn_NC_AVBR_VD3_Glutamate_neuron_to_neuron_exc_syn[1]")

        # Connection 0: cell 0, seg 0 (0.5) [0.5 on a_AVBR[0].soma] -> cell 0, seg 0 (0.5) [0.5 on a_VD3[0].soma], weight: 1.0, delay 0.0
        h("a_VD3[0].soma syn_NC_AVBR_VD3_Glutamate_neuron_to_neuron_exc_syn[0] = new neuron_to_neuron_exc_syn(0.5)")
        h("a_AVBR[0].soma a_VD3[0].synlist.append(new NetCon(&v(0.5), syn_NC_AVBR_VD3_Glutamate_neuron_to_neuron_exc_syn[0], -20.0, 0.0, 1.0))") # *->cell

        print("Processing 1 input lists")

        # ######################   Input List: Input_AVBR_offset_current
        # Adding single input: Component(id=0 type=input)
        h("objref Input_AVBR_offset_current_0")
        h("a_AVBR[0].soma { Input_AVBR_offset_current_0 = new offset_current(0.5) } ")

        print("Finished processing 1 input lists")

        trec = h.Vector()
        trec.record(h._ref_t)

        h.tstop = tstop

        if self.abs_tol is not None and self.rel_tol is not None:
            cvode = h.CVode()
            cvode.active(1)
            cvode.atol(self.abs_tol)
            cvode.rtol(self.rel_tol)
        else:
            h.dt = dt
            h.steps_per_ms = 1/h.dt

        # ######################   Display: self.display_neurons
        self.display_neurons = h.Graph(0)
        self.display_neurons.size(0,h.tstop,-80.0,50.0)
        self.display_neurons.view(0, -80.0, h.tstop, 130.0, 80, 330, 330, 250)
        h.graphList[0].append(self.display_neurons)
        # Line, plotting: AVBR/0/GenericNeuronCell/v
        self.display_neurons.addexpr("a_AVBR[0].soma.v(0.5)", "a_AVBR[0].soma.v(0.5)", 1, 1, 0.8, 0.9, 2)
        # Line, plotting: VD3/0/GenericNeuronCell/v
        self.display_neurons.addexpr("a_VD3[0].soma.v(0.5)", "a_VD3[0].soma.v(0.5)", 2, 1, 0.8, 0.9, 2)

        # ######################   Display: self.display_activity_neurons
        self.display_activity_neurons = h.Graph(0)
        self.display_activity_neurons.size(0,h.tstop,-80.0,50.0)
        self.display_activity_neurons.view(0, -80.0, h.tstop, 130.0, 80, 330, 330, 250)
        h.graphList[0].append(self.display_activity_neurons)
        # Line, plotting: AVBR/0/GenericNeuronCell/caConc
        self.display_activity_neurons.addexpr("a_AVBR[0].soma.cai(0.5)", "a_AVBR[0].soma.cai(0.5)", 1, 1, 0.8, 0.9, 2)
        # Line, plotting: VD3/0/GenericNeuronCell/caConc
        self.display_activity_neurons.addexpr("a_VD3[0].soma.cai(0.5)", "a_VD3[0].soma.cai(0.5)", 2, 1, 0.8, 0.9, 2)



        # ######################   File to save: MyNetwork.activity.dat (neurons_activity)
        # Column: AVBR/0/GenericNeuronCell/caConc
        h(' objectvar v_AVBR_v_neurons_activity ')
        h(' { v_AVBR_v_neurons_activity = new Vector() } ')
        h(' { v_AVBR_v_neurons_activity.record(&a_AVBR[0].soma.cai(0.5)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_AVBR_v_neurons_activity.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: VD3/0/GenericNeuronCell/caConc
        h(' objectvar v_VD3_v_neurons_activity ')
        h(' { v_VD3_v_neurons_activity = new Vector() } ')
        h(' { v_VD3_v_neurons_activity.record(&a_VD3[0].soma.cai(0.5)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_VD3_v_neurons_activity.resize((h.tstop * h.steps_per_ms) + 1)

        # ######################   File to save: MyNetwork.dat (neurons_v)
        # Column: AVBR/0/GenericNeuronCell/v
        h(' objectvar v_AVBR_v_neurons_v ')
        h(' { v_AVBR_v_neurons_v = new Vector() } ')
        h(' { v_AVBR_v_neurons_v.record(&a_AVBR[0].soma.v(0.5)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_AVBR_v_neurons_v.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: VD3/0/GenericNeuronCell/v
        h(' objectvar v_VD3_v_neurons_v ')
        h(' { v_VD3_v_neurons_v = new Vector() } ')
        h(' { v_VD3_v_neurons_v.record(&a_VD3[0].soma.v(0.5)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_VD3_v_neurons_v.resize((h.tstop * h.steps_per_ms) + 1)

        # ######################   File to save: time.dat (time)
        # Column: time
        h(' objectvar v_time ')
        h(' { v_time = new Vector() } ')
        h(' { v_time.record(&t) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_time.resize((h.tstop * h.steps_per_ms) + 1)

        self.initialized = False

        self.sim_end = -1 # will be overwritten

        setup_end = time.time()
        self.setup_time = setup_end - self.setup_start
        print("Setting up the network to simulate took %f seconds"%(self.setup_time))

        h.nrncontrolmenu()


    def run(self):

        self.initialized = True
        sim_start = time.time()
        if self.abs_tol is not None and self.rel_tol is not None:
            print("Running a simulation of %sms (cvode abs_tol = %sms, rel_tol = %sms; seed=%s)" % (h.tstop, self.abs_tol, self.rel_tol, self.seed))
        else:
            print("Running a simulation of %sms (dt = %sms; seed=%s)" % (h.tstop, h.dt, self.seed))

        try:
            h.run()
        except Exception as e:
            print("Exception running NEURON: %s" % (e))
            return


        self.sim_end = time.time()
        self.sim_time = self.sim_end - sim_start
        print("Finished NEURON simulation in %f seconds (%f mins)..."%(self.sim_time, self.sim_time/60.0))

        try:
            self.save_results()
        except Exception as e:
            print("Exception saving results of NEURON simulation: %s" % (e))
            return


    def advance(self):

        if not self.initialized:
            h.finitialize()
            self.initialized = True

        h.fadvance()


    ###############################################################################
    # Hash function to use in generation of random value
    # This is copied from NetPyNE: https://github.com/Neurosim-lab/netpyne/blob/master/netpyne/simFuncs.py
    ###############################################################################
    def _id32 (self,obj): 
        return int(hashlib.md5(obj.encode('utf-8')).hexdigest()[0:8],16)  # convert 8 first chars of md5 hash in base 16 to int


    ###############################################################################
    # Initialize the stim randomizer
    # This is copied from NetPyNE: https://github.com/Neurosim-lab/netpyne/blob/master/netpyne/simFuncs.py
    ###############################################################################
    def _init_stim_randomizer(self,rand, stimType, gid, seed): 
        #print("INIT STIM  %s; %s; %s; %s"%(rand, stimType, gid, seed))
        rand.Random123(self._id32(stimType), gid, seed)


    def save_results(self):

        print("Saving results at t=%s..."%h.t)

        if self.sim_end < 0: self.sim_end = time.time()

        self.display_neurons.exec_menu("View = plot")
        self.display_activity_neurons.exec_menu("View = plot")

        # ######################   File to save: time.dat (time). Note, saving in SI units
        py_v_time = [ t/1000 for t in h.v_time.to_python() ]  # Convert to Python list for speed...

        f_time_f2 = open('time.dat', 'w')
        num_points = len(py_v_time)  # Simulation may have been stopped before tstop...

        for i in range(num_points):
            f_time_f2.write('%f'% py_v_time[i])  # Save in SI units...
        f_time_f2.close()
        print("Saved data to: time.dat")

        # ######################   File to save: MyNetwork.activity.dat (neurons_activity). Note, saving in SI units
        py_v_AVBR_v_neurons_activity = [ float(x ) for x in h.v_AVBR_v_neurons_activity.to_python() ]  # Convert to Python list for speed, variable has dim: concentration
        py_v_VD3_v_neurons_activity = [ float(x ) for x in h.v_VD3_v_neurons_activity.to_python() ]  # Convert to Python list for speed, variable has dim: concentration

        f_neurons_activity_f2 = open('MyNetwork.activity.dat', 'w')
        num_points = len(py_v_time)  # Simulation may have been stopped before tstop...

        for i in range(num_points):
            f_neurons_activity_f2.write('%e\t%e\t%e\t\n' % (py_v_time[i], py_v_AVBR_v_neurons_activity[i], py_v_VD3_v_neurons_activity[i], ))
        f_neurons_activity_f2.close()
        print("Saved data to: MyNetwork.activity.dat")

        # ######################   File to save: MyNetwork.dat (neurons_v). Note, saving in SI units
        py_v_AVBR_v_neurons_v = [ float(x  / 1000.0) for x in h.v_AVBR_v_neurons_v.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_VD3_v_neurons_v = [ float(x  / 1000.0) for x in h.v_VD3_v_neurons_v.to_python() ]  # Convert to Python list for speed, variable has dim: voltage

        f_neurons_v_f2 = open('MyNetwork.dat', 'w')
        num_points = len(py_v_time)  # Simulation may have been stopped before tstop...

        for i in range(num_points):
            f_neurons_v_f2.write('%e\t%e\t%e\t\n' % (py_v_time[i], py_v_AVBR_v_neurons_v[i], py_v_VD3_v_neurons_v[i], ))
        f_neurons_v_f2.close()
        print("Saved data to: MyNetwork.dat")

        save_end = time.time()
        save_time = save_end - self.sim_end
        print("Finished saving results in %f seconds"%(save_time))

        print("Done")

if __name__ == '__main__':

    ns = NeuronSimulation(tstop=300.0, dt=0.01, seed=123456789, abs_tol=None, rel_tol=None)

    ns.run()

